# Application routes

home:
  url: /
  module: main
  action: index

profile:
  url: /profile
  module: main
  action: profile

skills:
  url: /profile/skills
  module: main
  action: skills

cards:
  url: /cards
  module: main
  action: cards

login:
  url: /login
  module: main
  action: login

logout:
  url: /logout
  module: main
  action: logout

play:
  url: /play
  module: main
  action: play

join:
  url: /join
  module: main
  action: join

forgot:
  url: /forgot
  module: main
  action: forgot

join-alpha:
  url: /join/:code
  module: main
  action: join

unavailable:
  url: /unavailable
  module: main
  action: unavailable

faq:
  url: /faq
  module: main
  action: faq

changelog:
  url: /changelog
  module: main
  action: changelog

media:
  url: /media
  module: main
  action: media

admin:
  url: /admin
  module: admin
  action: index

edit_cards:
  url: /admin/:card_type/cards
  module: admin
  action: cards

admin_card_of_the_week:
  url: /admin/cotw
  module: admin
  action: cardoftheweek

admin_reset_user_cards:
  url: /admin/reset/usercards
  module: admin
  action: resetusercards

admin_reset_games:
  url: /admin/reset/games
  module: admin
  action: resetgames

admin_news:
  url: /admin/news
  module: admin
  action: news

admin_skills:
  url: /admin/skills
  module: admin
  action: skills

edit_skill:
  url: /admin/skill/:skill_id
  module: admin
  action: editskill

new_skill:
  url: /admin/new/skill/*
  module: admin
  action: editskill

admin_users:
  url: /admin/users
  module: admin
  action: users

admin_games_finished:
  url: /admin/games/finished
  module: admin
  action: games
  parameters: {mode: 2}

admin_games_ongoing:
  url: /admin/games/ongoing
  module: admin
  action: games
  parameters: {mode: 1}

create_news:
  url: /admin/news/edit
  module: admin
  action: editnews
  parameters: {mode: new}

create_attack:
  url: /admin/attack/edit
  module: admin
  action: editattack

edit_attack:
  url: /admin/attack/edit/:attack_id
  module: admin
  action: editattack

edit_news:
  url: /admin/news/edit/:id
  module: admin
  action: editnews

news:
  url: /news/:year/:month/:day/:title/:id
  module: main
  action: news

admin_say:
  url: /admin/say
  module: admin
  action: say

new_card:
  url: /admin/:card_type/card
  module: admin
  action: card

edit_card:
  url: /admin/:card_type/card/:card_id
  module: admin
  action: card

get_backdrop_partial:
  url: /get/backdroppartial/:key/*
  module: main
  action: getbackdroppartial

profile:
  url: /profile
  module: main
  action: profile

lobby:
  url: /lobby
  module: lobby
  action: index

ask:
  url: /ask
  module: ask
  action: ask

say:
  url: /say
  module: ask
  action: say

room_say:
  url: /room/:room_id/say
  module: lobby
  action: say

market:
  url: /market
  module: market
  action: index

board:
  url: /board/:game_id/*
  module: game
  action: board

leave_game:
  url: /leave/game/:game_id
  module: game
  action: leavegame

training:
  url: game/training/:level
  module: game
  action: training

pick_cards:
  url: /cards/pick/:game_id/*
  module: game
  action: pickcards